---
- name: Download minio binary
  ansible.builtin.get_url:
    url: "https://dl.min.io/server/minio/release/linux-{{ go_arch }}/archive/minio.{{ minio_version }}"
    dest: "{{ minio_bin_directory }}/minio"
    owner: root
    group: root
    mode: 0111
    force: true
    checksum: "sha256:{{ __minio_checksum }}"
    timeout: 30
  retries: 5
  delay: 2
  notify:
    - Restart minio
  when: minio_installed_version.stdout < minio_version

- name: Create minio group
  ansible.builtin.group:
    name: "{{ minio_system_group }}"
    state: present
    system: true
  when: minio_system_group != "root"

- name: Create minio user
  ansible.builtin.user:
    name: "{{ minio_system_user }}"
    group: "{{ minio_system_group }}"
    shell: /usr/sbin/nologin
    system: true
    createhome: false
    home: /
  when: minio_system_user != "root"

- name: Create SSL storage directory
  ansible.builtin.file:
    path: "{{ minio_certs_dir }}"
    state: directory
    owner: "{{ minio_system_user }}"
    group: "{{ minio_system_group }}"
    mode: 0550

- name: Import environment file template
  ansible.builtin.template:
    src: minio.env.j2
    dest: /etc/default/minio
    owner: "{{ minio_system_user }}"
    group: "{{ minio_system_group }}"
    mode: 0440
  notify:
    - Restart minio

- name: Create storage directory
  ansible.builtin.file:
    path: "{{ minio_storage_dir }}"
    state: directory
    owner: "{{ minio_system_user }}"
    group: "{{ minio_system_group }}"
    mode: 0770

- name: Create systemd service unit
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/minio/minio-service/master/linux-systemd/minio.service"
    dest: "/etc/systemd/system/minio.service"
    owner: root
    group: root
    mode: 0644
    force: true
  notify:
    - Restart minio
